"""
AI-Powered Configuration Assistant

Uses Gemini to expand basic IP information into comprehensive detection configuration
including search keywords, visual markers, and AI tool detection patterns.
"""

import json
import os

from fastapi import APIRouter, HTTPException
from google import genai
from google.auth import default
from pydantic import BaseModel, Field

router = APIRouter()


class IPBasicInfo(BaseModel):
    """Minimal input from user - just name and company, Gemini does the rest!"""

    name: str = Field(..., description="Name of the intellectual property (e.g., 'Harry Potter', 'Spider-Man')")
    company: str = Field(..., description="Company name (e.g., 'Warner Bros', 'Disney', 'Sony')")
    explanation: str | None = Field(
        default=None,
        description="Additional context or specific instructions for Gemini (e.g., 'Focus on main trilogy only', 'Include Mandalorian series')"
    )
    priority: str | None = Field(
        default="medium",
        description="Business priority: low, medium, high, critical"
    )


class GeminiExpandedConfig(BaseModel):
    """Full configuration generated by Gemini"""

    # Basic info (Gemini researches and generates this)
    name: str
    owner: str = Field(..., description="Full legal copyright owner name")
    description: str = Field(..., description="Brief description of the IP")
    main_characters: list[str] = Field(..., description="All major characters")

    # Gemini-generated detection config - 3 PRIORITY TIERS
    high_priority_keywords: list[str] = Field(..., description="🔴 HIGH: Character + 'ai' generic keywords (scan every 3 days)")
    medium_priority_keywords: list[str] = Field(..., description="🟡 MEDIUM: Character + top AI tools - Sora, Runway, Kling, Pika (scan every 7 days)")
    low_priority_keywords: list[str] = Field(..., description="🟢 LOW: Character + niche AI tools - Luma, Veo, Minimax, Gen-2, Gen-3 (scan every 14 days)")

    visual_keywords: list[str] = Field(..., description="Visual detection markers for vision analysis")
    character_variations: list[str] = Field(..., description="All name variations and aliases")
    ai_tool_patterns: list[str] = Field(..., description="AI tool mentions to detect (e.g., 'sora spider-man')")
    common_video_titles: list[str] = Field(..., description="Common video title patterns to search for")
    false_positive_filters: list[str] = Field(..., description="Keywords that indicate false positives (toys, cosplay, etc.)")
    priority_weight: float = Field(..., description="Calculated priority weight (0.5-2.0)")
    monitoring_strategy: str = Field(..., description="Recommended monitoring strategy")

    # Metadata
    reasoning: str = Field(..., description="Gemini's reasoning for the configuration")


def create_keyword_expansion_prompt(ip_info: IPBasicInfo) -> str:
    """
    Creates a comprehensive prompt for Gemini to generate AI detection configuration.

    INPUT: Just IP name + company
    OUTPUT: Complete monitoring configuration with keywords, visual markers, etc.

    Gemini uses its knowledge to fill in ALL the details!
    """

    # Build additional context section if explanation provided
    additional_context = ""
    if ip_info.explanation:
        additional_context = f"""

# USER PROVIDED CONTEXT

The user has provided specific instructions and context:

{ip_info.explanation}

**IMPORTANT:** You MUST follow these specific instructions when generating the configuration. Prioritize this user context over your general knowledge.
"""

    return f"""You are an expert in copyright infringement detection and AI-generated content monitoring. Your task is to generate a comprehensive detection configuration for monitoring AI-generated videos that may infringe on this intellectual property.

# INPUT INFORMATION

**IP Name:** {ip_info.name}
**Company:** {ip_info.company}
**Business Priority:** {ip_info.priority}
{additional_context}

# YOUR TASK - PART 1: RESEARCH THE IP

Using your knowledge{' and the user-provided context above' if ip_info.explanation else ''}, identify:
1. **Main characters** - All major characters in this franchise/IP
2. **Visual signatures** - Distinctive visual elements (costumes, weapons, symbols, locations)
3. **Story elements** - Key plot points, settings, iconic scenes
4. **Copyright owner** - Full legal entity name
5. **Franchise value** - How commercially valuable/popular is this IP?

# YOUR TASK

Generate a complete detection configuration optimized for finding AI-generated YouTube videos featuring this IP.

## 1. SEARCH KEYWORDS - PRIORITIZED CHARACTER × AI TOOL MATRIX

🚨 **GENERATION STRATEGY: Create prioritized character + AI tool combinations** 🚨

### Step 1: Identify ALL Characters
List ALL major characters from {ip_info.name}:
- Main protagonists (5-10 characters)
- Main antagonists (3-5 villains)
- Popular supporting characters (5-10 characters)

### Step 2: AI Video Tools (PRIORITIZED)
For EACH character, generate keywords with these AI video generation tools IN PRIORITY ORDER:

**🔴 HIGH PRIORITY (scan every 3 days):**
- `ai` (generic catch-all - finds most AI content)

**🟡 MEDIUM PRIORITY (scan every 7 days):**
- `sora` (OpenAI Sora - very popular)
- `runway` (Runway ML - very popular)
- `kling` (Kling AI - growing)
- `pika` (Pika Labs - popular)

**🟢 LOW PRIORITY (scan every 14 days):**
- `luma` (Luma Dream Machine)
- `veo` (Google Veo)
- `veo3` (Google Veo 3)
- `minimax` (Minimax AI)
- `gen-2` (Runway Gen-2)
- `gen-3` (Runway Gen-3)

**Format:** `{{character_name}} {{ai_tool}}`

### Step 3: Generate Prioritized Matrix

For **EACH character**, create keywords with **EACH AI tool**, grouped by priority:

**Example Matrix for Superman:**

**High Priority (scan first):**
```
superman ai
```

**Medium Priority:**
```
superman sora
superman runway
superman kling
superman pika
```

**Low Priority:**
```
superman luma
superman veo
superman veo3
superman minimax
superman gen-2
superman gen-3
```
**(11 keywords per character: 1 high, 4 medium, 6 low)**

**Example Matrix for Batman:**

**High Priority:**
```
batman ai
```

**Medium Priority:**
```
batman sora
batman runway
batman kling
batman pika
```

**Low Priority:**
```
batman luma
batman veo
batman veo3
batman minimax
batman gen-2
batman gen-3
```
**(11 keywords per character: 1 high, 4 medium, 6 low)**

### Step 4: Add Franchise-Level Keywords (Prioritized)

For the main franchise, movies, games, or major properties, use the same prioritized AI tool pattern:

**Example for DC Universe:**

**High Priority:**
```
justice league ai
batman movie ai
superman returns ai
wonder woman 1984 ai
```

**Medium Priority:**
```
justice league sora
justice league runway
batman movie runway
```

### Step 5: Add Location/Object Keywords (All High Priority)

For iconic locations, vehicles, or objects (always use generic "ai" for broad coverage):
```
gotham city ai
metropolis ai
batmobile ai
fortress of solitude ai
daily planet ai
```

### TARGET KEYWORD COUNT

**Calculate total keywords:**
- 10 main characters × 11 AI tools = **110 keywords**
  - 10 high priority (character + ai)
  - 40 medium priority (character + top 4 tools)
  - 60 low priority (character + remaining tools)
- 5 franchise properties × (1 high + 2 medium) = **15 keywords**
- 10 locations/objects × "ai" = **10 keywords** (all high priority)
- **TOTAL: ~135 keywords (25 high, 55 medium, 60 low)**

### COMPLETE EXAMPLE - Justice League (First 3 Characters)

**Characters:** Superman, Batman, Wonder Woman, Flash, Aquaman, Green Lantern, Cyborg, Joker, Harley Quinn, Lex Luthor

**Generated Keywords with Priority Tags:**

```json
{{
  "high_priority_keywords": [
    "superman ai",
    "batman ai",
    "wonder woman ai",
    "flash ai",
    "aquaman ai",
    "green lantern ai",
    "cyborg ai",
    "joker ai",
    "harley quinn ai",
    "lex luthor ai",
    "justice league ai",
    "batman movie ai",
    "gotham city ai",
    "metropolis ai",
    "batmobile ai"
  ],
  "medium_priority_keywords": [
    "superman sora", "superman runway", "superman kling", "superman pika",
    "batman sora", "batman runway", "batman kling", "batman pika",
    "wonder woman sora", "wonder woman runway", "wonder woman kling", "wonder woman pika",
    "justice league sora", "justice league runway"
  ],
  "low_priority_keywords": [
    "superman luma", "superman veo", "superman veo3", "superman minimax", "superman gen-2", "superman gen-3",
    "batman luma", "batman veo", "batman veo3", "batman minimax", "batman gen-2", "batman gen-3",
    "wonder woman luma", "wonder woman veo", "wonder woman veo3", "wonder woman minimax", "wonder woman gen-2", "wonder woman gen-3"
  ]
}}
```

## 2. VISUAL KEYWORDS (10-15 items)

Visual markers that identify this IP in video frames. Be SPECIFIC and DISTINCTIVE:
- Costume/outfit details (colors, patterns, symbols)
- Signature accessories or weapons
- Unique physical features
- Characteristic poses or actions
- Iconic locations or settings

**Example for Batman:**
- "bat symbol on chest", "black cape", "cowl with pointed ears", "utility belt"
- "gotham cityscape", "batmobile", "bat signal in sky"

## 3. CHARACTER VARIATIONS (all possible names/aliases)

List every possible way this character/IP could be referenced:
- Full names
- Nicknames
- Alter egos
- Code names
- Common misspellings
- Non-English variations if globally known

## 4. AI TOOL PATTERNS (10-15 detection markers)

Text patterns that indicate AI-generated content. These are for DETECTION, not search (used in vision analysis):
- "sora", "runway", "kling", "pika", "luma", "minimax"
- "ai generated", "ai movie", "made with ai", "created with"
- "text to video", "video ai", "artificial intelligence"
- Tool mentions in titles/descriptions
- NOT for YouTube searches (too narrow), only for identifying AI content

## 5. COMMON VIDEO TITLES (10-15 patterns)

How do people typically title AI-generated videos of this IP? Examples:
- "I made a {{IP}} movie with Sora AI"
- "{{Character}} vs {{Villain}} - AI Generated"
- "{{IP}} - Full AI Short Film"
- "What if {{Character}} was in {{scenario}} | AI"
- "{{IP}} Trailer - Made with {{AI Tool}}"

## 6. FALSE POSITIVE FILTERS (8-12 keywords)

Keywords that indicate this is NOT infringement (filter these out):
- "review", "reaction", "analysis", "breakdown"
- "toy", "figure", "cosplay", "costume tutorial"
- "gameplay", "game", "lego", "minecraft"
- "drawing", "sketch", "painting", "art tutorial"
- "news", "interview", "behind the scenes"

These indicate fair use, real footage, or non-AI content.

## 7. PRIORITY WEIGHT (0.5 - 2.0)

**IMPORTANT:** The user selected priority "{ip_info.priority}". Match this priority level.

Based on user selection, assign a weight:
- **low**: 0.7 (selective monitoring)
- **medium**: 1.0 (standard monitoring)
- **high**: 1.5 (aggressive monitoring) ← USER SELECTED
- **critical**: 2.0 (maximum protection)

Set priority_weight to match the user's selection above.

## 8. MONITORING STRATEGY

**IMPORTANT:** Match the user's priority "{ip_info.priority}":
- **low** → "selective" (lower priority, higher threshold)
- **medium** → "balanced" (standard monitoring)
- **high** → "aggressive" (scan frequently, low threshold) ← USER SELECTED
- **critical** → "aggressive" (maximum protection)

## 9. REASONING

Explain your choices:
- Why these keywords will be effective
- What makes the visual markers distinctive
- Expected infringement patterns
- Risk assessment

# OUTPUT FORMAT

Respond with a valid JSON object matching this schema:

{{
  "name": "{ip_info.name}",
  "owner": "Full legal entity name (e.g., 'Warner Bros. Entertainment Inc.')",
  "description": "Brief description of the IP and franchise",
  "main_characters": ["character1", "character2", ...],
  "high_priority_keywords": ["character1 ai", "character2 ai", "location ai", ...],
  "medium_priority_keywords": ["character1 sora", "character1 runway", "character1 kling", "character1 pika", ...],
  "low_priority_keywords": ["character1 luma", "character1 veo", "character1 veo3", "character1 minimax", "character1 gen-2", "character1 gen-3", ...],
  "visual_keywords": ["marker1", "marker2", ...],
  "character_variations": ["name1", "alias1", ...],
  "ai_tool_patterns": ["ip ai_tool", ...],
  "common_video_titles": ["pattern1", "pattern2", ...],
  "false_positive_filters": ["filter1", "filter2", ...],
  "priority_weight": 1.5,
  "monitoring_strategy": "aggressive|balanced|selective|targeted",
  "reasoning": "Detailed explanation of why this configuration will effectively detect AI-generated infringement..."
}}

**CRITICAL:** You MUST populate all 3 keyword tiers (high_priority_keywords, medium_priority_keywords, low_priority_keywords). This is the ONLY keyword format supported - no legacy fields.

# IMPORTANT GUIDELINES

1. **PRIORITY STRATEGY** - High priority keywords (character + "ai") are scanned most frequently (every 3 days). Medium priority (specific tools) every 7 days. Low priority every 14 days
2. **HIGH PRIORITY = BROAD** - "batman ai" finds most content (scan often). Better ROI than tool-specific keywords
3. **MEDIUM PRIORITY = POPULAR TOOLS** - Only sora, runway, kling, pika (most used AI tools). Scan weekly
4. **LOW PRIORITY = NICHE TOOLS** - Less popular tools (luma, veo, minimax, gen-2, gen-3). Scan bi-weekly
5. **Think like a creator** - Most people title videos "Batman AI Movie", not "Batman Sora AI Generated"
6. **Cost efficiency** - High-priority keywords get scanned more often because they return more results per scan
7. **Balance precision and recall** - High priority for broad discovery, medium/low for comprehensive coverage

Generate the configuration now."""


async def generate_config_with_gemini(ip_info: IPBasicInfo) -> GeminiExpandedConfig:
    """
    Uses Gemini to expand minimal IP info into full detection configuration.
    """

    # Get project from env (not default credentials in local dev)
    project = os.getenv("GEMINI_PROJECT_ID")
    if not project:
        raise HTTPException(status_code=500, detail="GEMINI_PROJECT_ID not configured")

    region = os.getenv("GEMINI_LOCATION", "europe-west1")

    # Initialize Gemini client
    try:
        _credentials, _ = default()
        client = genai.Client(
            vertexai=True,
            project=project,
            location=region
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to initialize Gemini client: {e!s}")

    # Create prompt
    prompt = create_keyword_expansion_prompt(ip_info)

    # Generate with Gemini 2.5 Flash (fast, cheap, good at structured output)
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={
                "temperature": 0.7,  # Some creativity, but mostly focused
                "max_output_tokens": 50000,  # Gemini 2.5 Flash max output
                "response_mime_type": "application/json"  # Force JSON output
            }
        )

        # Parse JSON response
        config_data = json.loads(response.text)

        # Validate and return
        return GeminiExpandedConfig(**config_data)

    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to parse Gemini response as JSON: {e}\n\nResponse: {response.text}"
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Gemini API error: {e!s}"
        )


@router.post("/generate", response_model=GeminiExpandedConfig)
async def generate_ip_configuration(ip_info: IPBasicInfo):
    """
    Generate comprehensive IP detection configuration using Gemini AI.

    **Input:** Just IP name + company (Gemini figures out the rest!)
    **Output:** Full configuration with keywords, visual markers, detection patterns

    **Example:**
    ```json
    {
      "name": "Harry Potter",
      "company": "Warner Bros"
    }
    ```

    Gemini will automatically research and generate:
    - All main characters (Harry, Hermione, Ron, Voldemort, etc.)
    - Visual markers (lightning scar, wands, Hogwarts, house robes)
    - Search keywords optimized for AI-generated content
    - AI tool patterns (Harry Potter + Sora, Runway, etc.)
    - False positive filters
    - Priority scoring

    **Returns:** Complete configuration ready to use for monitoring.
    """

    config = await generate_config_with_gemini(ip_info)
    return config


@router.post("/preview", response_model=dict)
async def preview_search_results(config: GeminiExpandedConfig):
    """
    Preview what the generated keywords would find (shows example searches).

    Returns estimated match rates and sample video titles for validation.
    """

    # Return preview data
    return {
        "total_keywords": len(config.search_keywords),
        "ai_tool_combinations": len(config.ai_tool_patterns),
        "estimated_daily_matches": len(config.search_keywords) * 50,  # Rough estimate
        "sample_searches": config.search_keywords[:5],
        "visual_markers_count": len(config.visual_keywords),
        "false_positive_filters_count": len(config.false_positive_filters),
        "priority_weight": config.priority_weight,
        "recommendation": config.monitoring_strategy
    }


# ============================================================================
# SECTION-SPECIFIC SUGGESTION ENDPOINTS
# ============================================================================

class SuggestRequest(BaseModel):
    """Request to suggest more items for a specific section."""
    ip_name: str
    existing_items: list[str]
    user_prompt: str | None = None  # Optional user description of what they want


class SuggestResponse(BaseModel):
    """Response with suggested items."""
    suggestions: list[str]




async def call_gemini_for_suggestions(prompt: str) -> list[str]:
    """Helper to call Gemini and parse suggestions."""
    project = os.getenv("GEMINI_PROJECT_ID")
    if not project:
        raise HTTPException(status_code=500, detail="GEMINI_PROJECT_ID not configured")

    region = os.getenv("GEMINI_LOCATION", "europe-west1")

    try:
        _credentials, _ = default()
        client = genai.Client(
            vertexai=True,
            project=project,
            location=region
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to initialize Gemini client: {e!s}")

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={
                "temperature": 0.8,  # More creativity for suggestions
                "max_output_tokens": 4096,  # Smaller response for lists
                "response_mime_type": "application/json"
            }
        )

        data = json.loads(response.text)
        return data.get("suggestions", [])

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini error: {e!s}")


@router.post("/suggest-characters", response_model=SuggestResponse)
async def suggest_characters(request: SuggestRequest):
    """Suggest additional characters for the IP."""
    user_guidance = f"\n\nUser Request: {request.user_prompt}\n\nIMPORTANT: Follow the user's request closely. If they specify a number (e.g., '20 villains'), return that exact number." if request.user_prompt else ""

    prompt = f"""Given this IP: "{request.ip_name}"

Existing characters: {', '.join(request.existing_items)}{user_guidance}

Generate more characters according to the user's request. If no specific number mentioned, suggest a reasonable amount (typically 5-10).
{f'Focus specifically on: {request.user_prompt}' if request.user_prompt else '''Focus on:
- Main characters (protagonists, antagonists)
- Supporting characters
- Popular characters from the franchise
- Well-known characters that fans would recognize'''}

Return JSON: {{"suggestions": ["Character Name 1", "Character Name 2", ...]}}

IMPORTANT:
- Only suggest characters that ACTUALLY belong to "{request.ip_name}"
- Use proper character names (not descriptions)
- DO NOT repeat existing characters
- Only suggest NEW ones that are not in the existing list
{f'- Follow the user request precisely: {request.user_prompt}' if request.user_prompt else ''}"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)


@router.post("/suggest-keywords", response_model=SuggestResponse)
async def suggest_keywords(request: SuggestRequest):
    """Suggest additional search keywords for YouTube discovery using CHARACTER × AI TOOL matrix."""

    # Parse number from user prompt
    requested_count = 20  # default
    if request.user_prompt:
        import re
        match = re.search(r'(\d+)', request.user_prompt)
        if match:
            requested_count = int(match.group(1))

    prompt = f"""Generate YouTube search keywords for IP: "{request.ip_name}"

🚨 **MANDATORY: Generate FULL CHARACTER × AI TOOL MATRIX** 🚨

## CRITICAL INSTRUCTION

You MUST generate keywords for EACH character with EVERY AI tool listed below.
DO NOT skip AI tools. DO NOT be selective. Generate the COMPLETE matrix.

## Step 1: List Characters from "{request.ip_name}"
Identify all characters that belong to this IP (NOT other IPs!).

## Step 2: Generate FULL Character × AI Tool Matrix

For **EVERY SINGLE CHARACTER**, create keywords with **ALL 11 AI tools**:

**Core AI Tools (YOU MUST USE ALL 11 FOR EACH CHARACTER):**
1. ai (generic)
2. sora (OpenAI Sora)
3. runway (Runway ML)
4. kling (Kling AI)
5. pika (Pika Labs)
6. luma (Luma Dream Machine)
7. veo (Google Veo)
8. veo3 (Google Veo 3)
9. minimax (Minimax AI)
10. gen-2 (Runway Gen-2)
11. gen-3 (Runway Gen-3)

**Format:** `{{character}} {{ai_tool}}`

**MANDATORY PATTERN:**
If you have 5 characters, you MUST generate 5 × 11 = 55 keywords minimum

## Example Matrix

If IP = "DC Universe" with characters [Batman, Superman, Joker]:

```
# Batman
batman ai
batman sora
batman runway
batman kling
batman pika
batman luma
batman veo
batman veo3
batman minimax
batman gen-2
batman gen-3

# Superman
superman ai
superman sora
superman runway
superman kling
superman pika
superman luma
superman veo
superman veo3
superman minimax
superman gen-2
superman gen-3

# Joker
joker ai
joker sora
joker runway
joker kling
joker pika
joker luma
joker veo
joker veo3
joker minimax
joker gen-2
joker gen-3
```

## Step 3: Add Franchise/Movie/Game Keywords

If this IP has famous movies, games, or franchise names, add those too:

**Example:**
```
justice league ai
justice league sora
batman movie ai
superman returns ai
wonder woman 1984 ai
gotham city ai
metropolis ai
```

## VALIDATION RULES

✅ **CORRECT** - Character + AI tool:
- "batman ai"
- "superman sora"
- "wonder woman runway"
- "joker kling"
- "flash veo3"

❌ **WRONG** - Characters from OTHER IPs:
- "spider-man ai" (Marvel, not {request.ip_name}!)
- "mickey mouse ai" (Disney, not {request.ip_name}!)
- "mario ai" (Nintendo, not {request.ip_name}!)

❌ **WRONG** - Missing AI tool:
- "batman movie" (no AI tool!)
- "superman trailer" (no AI tool!)

❌ **WRONG** - Too creative/narrow:
- "batman ai concept art"
- "superman ai behind the scenes"

## YOUR TASK

Generate {requested_count} NEW keywords following the FULL MATRIX approach.

**Existing keywords to SKIP:** {', '.join(request.existing_items)}

**CRITICAL RULES:**
1. For EACH character, generate keywords with ALL 11 AI tools (not just 1-2!)
2. If you identify 3 new characters, generate 3 × 11 = 33 keywords
3. DO NOT be selective - include ALL AI tool combinations
4. Only use characters from "{request.ip_name}" IP!

**EXAMPLE OF CORRECT GENERATION:**
If adding "Joker" character:
- joker ai
- joker sora
- joker runway
- joker kling
- joker pika
- joker luma
- joker veo
- joker veo3
- joker minimax
- joker gen-2
- joker gen-3
(ALL 11 tools for ONE character = 11 keywords)

**WRONG - INCOMPLETE:**
If adding "Joker" but only generating:
- joker ai
- joker gen-3
(Only 2 tools - REJECTED! Must use all 11!)

Return JSON: {{"suggestions": ["keyword1", "keyword2", ...]}}

REMINDER: Generate the FULL matrix - every character × every AI tool!"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)


@router.post("/suggest-ai-patterns", response_model=SuggestResponse)
async def suggest_ai_patterns(request: SuggestRequest):
    """Suggest additional AI tool detection patterns."""
    user_guidance = f"\n\nUser Request: {request.user_prompt}\n\nIMPORTANT: Follow the user's request closely. If they specify a number, return that exact number." if request.user_prompt else ""

    prompt = f"""Given this IP: "{request.ip_name}"

Existing AI patterns: {', '.join(request.existing_items)}{user_guidance}

Generate more AI tool detection patterns according to the user's request. If no specific number mentioned, suggest a reasonable amount (typically 5-10).
{f'Focus specifically on: {request.user_prompt}' if request.user_prompt else '''Focus on:
- AI tool mentions (Sora, Runway, Kling, Pika, Luma, etc.)
- Gen-AI phrases ("AI generated", "made with AI", "text to video")
- Tool-specific watermarks
- Creator mentions ("created with", "powered by")'''}

Return JSON: {{"suggestions": ["pattern1", "pattern2", ...]}}

DO NOT repeat existing patterns. Only suggest NEW ones.
{f'Follow the user request precisely: {request.user_prompt}' if request.user_prompt else ''}"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)


@router.post("/suggest-visual-keywords", response_model=SuggestResponse)
async def suggest_visual_keywords(request: SuggestRequest):
    """Suggest additional visual detection keywords."""
    user_guidance = f"\n\nUser Request: {request.user_prompt}\n\nIMPORTANT: Follow the user's request closely. If they specify a number, return that exact number." if request.user_prompt else ""

    prompt = f"""Given this IP: "{request.ip_name}"

Existing visual keywords: {', '.join(request.existing_items)}{user_guidance}

Generate more visual keywords according to the user's request. If no specific number mentioned, suggest a reasonable amount (typically 5-10).
{f'Focus specifically on: {request.user_prompt}' if request.user_prompt else '''Focus on:
- Distinctive visual elements (costumes, props, symbols)
- Character visual markers (logos, colors, styles)
- Location markers (iconic settings)
- Visual signatures unique to this IP'''}

Return JSON: {{"suggestions": ["keyword1", "keyword2", ...]}}

DO NOT repeat existing keywords. Only suggest NEW ones.
{f'Follow the user request precisely: {request.user_prompt}' if request.user_prompt else ''}"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)


@router.post("/suggest-video-titles", response_model=SuggestResponse)
async def suggest_video_titles(request: SuggestRequest):
    """Suggest common video title patterns."""
    user_guidance = f"\n\nUser Request: {request.user_prompt}\n\nIMPORTANT: Follow the user's request closely. If they specify a number, return that exact number." if request.user_prompt else ""

    prompt = f"""Given this IP: "{request.ip_name}"

Existing title patterns: {', '.join(request.existing_items)}{user_guidance}

Generate more video title patterns according to the user's request. If no specific number mentioned, suggest a reasonable amount (typically 5-10).
{f'Focus specifically on: {request.user_prompt}' if request.user_prompt else '''Focus on:
- Clickbait patterns ("I made X with AI", "AI creates X")
- Comparison patterns ("X vs AI", "Real vs AI X")
- Showcase patterns ("X in Sora", "Runway generated X")
- Viral patterns ("You won't believe...", "AI X is insane")'''}

Return JSON: {{"suggestions": ["pattern1", "pattern2", ...]}}

DO NOT repeat existing patterns. Only suggest NEW ones.
{f'Follow the user request precisely: {request.user_prompt}' if request.user_prompt else ''}"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)


@router.post("/suggest-false-positive-filters", response_model=SuggestResponse)
async def suggest_false_positive_filters(request: SuggestRequest):
    """Suggest false positive filters."""
    user_guidance = f"\n\nUser Request: {request.user_prompt}\n\nIMPORTANT: Follow the user's request closely. If they specify a number, return that exact number." if request.user_prompt else ""

    prompt = f"""Given this IP: "{request.ip_name}"

Existing filters: {', '.join(request.existing_items)}{user_guidance}

Generate more false positive filters according to the user's request. If no specific number mentioned, suggest a reasonable amount (typically 5-10).
{f'Focus specifically on: {request.user_prompt}' if request.user_prompt else '''Focus on:
- Non-infringement indicators (toys, cosplay, reviews)
- Educational/Fair use (analysis, commentary, parody)
- Gaming content (gameplay, mod, fan game)
- Official content markers (trailer, official, licensed)'''}

Return JSON: {{"suggestions": ["filter1", "filter2", ...]}}

DO NOT repeat existing filters. Only suggest NEW ones.
{f'Follow the user request precisely: {request.user_prompt}' if request.user_prompt else ''}"""

    suggestions = await call_gemini_for_suggestions(prompt)
    return SuggestResponse(suggestions=suggestions)
